name: Build Multi-Platform Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create macOS executable with PyInstaller
      run: |
        pyinstaller packing/CppStructParser-macos.spec
        
    - name: Smoke test the macOS executable
      run: |
        ./dist/CppStructParser &
        sleep 5
        pkill -f CppStructParser || echo "Process not found or already stopped"
      shell: bash

    - name: Upload macOS executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CppStructParser-macOS
        path: dist/CppStructParser

  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Windows executable with PyInstaller
      run: |
        pyinstaller packing/CppStructParser-windows.spec
        
    - name: Smoke test the Windows executable
      run: |
        Start-Process -FilePath dist/CppStructParser.exe
        Start-Sleep -Seconds 5
        Get-Process CppStructParser -ErrorAction SilentlyContinue | Stop-Process
      shell: pwsh

    - name: Upload Windows executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CppStructParser-Windows
        path: dist/CppStructParser.exe 