name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create executable with PyInstaller
      run: |
        pyinstaller CppStructParser.spec
        
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CppStructParser-Windows
        path: dist/CppStructParser.exe
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/CppStructParser.exe
        asset_name: CppStructParser-Windows.exe
        asset_content_type: application/octet-stream 