name: PR Test & Distribute

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-distribute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system GUI dependencies (Xvfb, Tk)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y xvfb python3-tk

    - name: Set up virtual environment
      run: |
        python -m venv .venv
        . .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all tests
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        .venv/bin/python run_all_tests.py

    - name: Distribute (build executables)
      run: |
        python packing/build.py --target all
